// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewOrder struct {
	ID           string `json:"id"`
	CustomerName string `json:"customer_name"`
	OrderItemID  string `json:"orderItemId"`
}

type Order struct {
	ID           string `json:"id"`
	CustomerName string `json:"customer_name"`
	OrderItemID  string `json:"orderItemId"`
}

type Query struct {
}
